(ns stockroom.v1.permissions)

(def all-permissions
  #{"user-administration"
    "user-administration/read-only"
    "clients"
    "clients/read-only"
    "skills"
    "skills/read-only"
    "employees"
    "employees/read-only"
    "engagements"
    "engagements/read-only"
    "people"
    "people/read-only"
    "projects"
    "projects/read-only"
    "sows"
    "sows/read-only"
    "project-sows"
    "project-sows/read-only"
    "project-skills"
    "project-skills/read-only"
    "apprenticeships"
    "apprenticeships/read-only"
    "location-memberships"
    "location-memberships/read-only"
    "locations"
    "locations/read-only"})
